#!/usr/bin/perl

open(FF, "| msgfmt -o - -");
while (defined($in = <stdin>)) {
    @str = split(//, $in);
    for($i=0; $i<=$#str; $i++) {
        $_ = $str[$i];
        if (/[\x80-\xff]/ && $i<=$#str-1) {
            printf(FF "$str[$i]");
            $_ = $str[$i+1];
            (/[\\]/) ? printf(FF "\\\\") : printf(FF "$str[$i+1]");
            $i++;
	}
        else {
	    printf(FF "$str[$i]");
	}
    }
}
close(FF);
